import type { Recipe } from "./types";

export const recipes: Recipe[] = [
  {
    id: "1",
    name: "Ensalada de Pasta de Verano",
    description:
      "Una ensalada de pasta refrescante y ligera, perfecta para los cálidos días de verano.",
    ingredients: [
      { item: "Pasta fusilli", amount: "250g" },
      { item: "Tomates cherry", amount: "200g, partidos a la mitad" },
      { item: "Pepino", amount: "1, en cubos" },
      { item: "Queso feta", amount: "100g, desmenuzado" },
      { item: "Aceite de oliva", amount: "3 cdas" },
      { item: "Jugo de limón", amount: "1 cda" },
    ],
    instructions: [
      "Cocina la pasta según las instrucciones del paquete. Escúrrela y enjuágala con agua fría.",
      "En un tazón grande, combina la pasta, los tomates, el pepino y el queso feta.",
      "En un tazón pequeño, bate el aceite de oliva y el jugo de limón. Sazona con sal y pimienta.",
      "Vierte el aderezo sobre la ensalada y mezcla para combinar.",
    ],
    prepTime: "15 min",
    cookTime: "10 min",
    servings: 4,
    tags: ["vegetariano", "ensalada", "verano"],
    image: "pasta-salad",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "2",
    name: "Pollo al Curry Picante",
    description: "Un rico y aromático pollo al curry con un toque picante.",
    ingredients: [
      { item: "Pechuga de pollo", amount: "500g, en cubos" },
      { item: "Cebolla", amount: "1, picada" },
      { item: "Ajo", amount: "2 dientes, picados" },
      { item: "Jengibre", amount: "1 pulgada, rallado" },
      { item: "Leche de coco", amount: "400ml" },
      { item: "Curry en polvo", amount: "2 cdas" },
    ],
    instructions: [
      "Calienta aceite en una sartén grande. Sofríe la cebolla, el ajo y el jengibre hasta que estén fragantes.",
      "Añade el pollo y cocínalo hasta que se dore.",
      "Incorpora el curry en polvo y cocina por 1 minuto.",
      "Vierte la leche de coco, llévalo a ebullición y cocina a fuego lento durante 15-20 minutos hasta que el pollo esté bien cocido.",
    ],
    prepTime: "10 min",
    cookTime: "25 min",
    servings: 4,
    tags: ["curry", "picante"],
    image: "chicken-curry",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "3",
    name: "Tacos de Frijoles Negros",
    description:
      "Tacos veganos sabrosos y satisfactorios con una crema de lima ácida.",
    ingredients: [
      { item: "Frijoles negros", amount: "1 lata, enjuagados" },
      { item: "Tortillas de maíz", amount: "8" },
      { item: "Cebolla roja", amount: "1/2, en cubos" },
      { item: "Cilantro", amount: "1/4 taza, picado" },
      { item: "Aguacate", amount: "1, en rodajas" },
      { item: "Lima", amount: "1, el jugo" },
    ],
    instructions: [
      "En un tazón, machaca la mitad de los frijoles negros. Mezcla los frijoles enteros, la cebolla y el cilantro.",
      "Calienta las tortillas en una sartén seca.",
      "Reparte la mezcla de frijoles en las tortillas.",
      "Cubre con rodajas de aguacate y un chorrito de jugo de lima.",
    ],
    prepTime: "20 min",
    cookTime: "5 min",
    servings: 2,
    tags: ["vegano", "tacos", "mexicano"],
    image: "vegan-tacos",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "4",
    name: "Pastel de Chocolate Decadente",
    description:
      "Un pastel de chocolate húmedo y chocolatoso que es sorprendentemente fácil de hacer.",
    ingredients: [
      { item: "Harina para todo uso", amount: "2 tazas" },
      { item: "Azúcar", amount: "2 tazas" },
      { item: "Cacao en polvo sin azúcar", amount: "3/4 taza" },
      { item: "Bicarbonato de sodio", amount: "2 cditas" },
      { item: "Huevos", amount: "2" },
      { item: "Suero de leche", amount: "1 taza" },
    ],
    instructions: [
      "Precalienta el horno a 350°F (175°C). Engrasa y enharina dos moldes redondos de 9 pulgadas.",
      "En un tazón grande, mezcla la harina, el azúcar, el cacao, el bicarbonato de sodio y la sal.",
      "Añade los huevos, el suero de leche, el aceite y la vainilla. Bate a velocidad media durante 2 minutos.",
      "Incorpora el agua hirviendo. La masa estará líquida.",
      "Vierte uniformemente en los moldes preparados.",
      "Hornea de 30 a 35 minutos.",
    ],
    prepTime: "20 min",
    cookTime: "35 min",
    servings: 12,
    tags: ["postre", "pastel", "chocolate"],
    image: "chocolate-cake",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "5",
    name: "Tostada Clásica de Aguacate",
    description: "Un desayuno o snack simple, saludable y delicioso.",
    ingredients: [
      { item: "Pan de masa madre", amount: "2 rebanadas" },
      { item: "Aguacate", amount: "1, maduro" },
      { item: "Huevo", amount: "1" },
      { item: "Hojuelas de pimiento rojo", amount: "una pizca" },
    ],
    instructions: [
      "Tuesta el pan de masa madre a tu gusto.",
      "Machaca el aguacate y úntalo sobre la tostada.",
      "Escalfa o fríe un huevo y colócalo encima del aguacate.",
      "Espolvorea con hojuelas de pimiento rojo, sal y pimienta.",
    ],
    prepTime: "5 min",
    cookTime: "5 min",
    servings: 1,
    tags: ["desayuno", "vegetariano", "saludable"],
    image: "avocado-toast",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "6",
    name: "Salmón a la Parrilla Simple",
    description:
      "Un plato principal rápido y elegante de salmón con limón y hierbas.",
    ingredients: [
      { item: "Filetes de salmón", amount: "2" },
      { item: "Aceite de oliva", amount: "1 cda" },
      { item: "Limón", amount: "1" },
      { item: "Eneldo fresco", amount: "2 ramitas" },
    ],
    instructions: [
      "Precalienta la parrilla a fuego medio-alto.",
      "Unta el salmón con aceite de oliva y sazona con sal y pimienta.",
      "Asa con la piel hacia abajo durante 5-7 minutos.",
      "Voltea y cocina por otros 3-5 minutos, hasta que esté bien cocido.",
      "Sirve con un chorrito de limón y eneldo fresco.",
    ],
    prepTime: "5 min",
    cookTime: "12 min",
    servings: 2,
    tags: ["saludable", "pescados y mariscos", "sin gluten"],
    image: "grilled-salmon",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "7",
    name: "Milanesas de Pollo",
    description:
      "Crujientes milanesas de pollo, perfectas para servir con puré o ensalada.",
    ingredients: [
      { item: "Pechugas de pollo", amount: "4, fileteadas" },
      { item: "Huevos", amount: "2" },
      { item: "Pan rallado", amount: "2 tazas" },
      { item: "Ajo en polvo", amount: "1 cdita" },
      { item: "Perejil", amount: "2 cdas, picado" },
      { item: "Aceite", amount: "para freír" },
      { item: "Limón", amount: "1, para servir" },
    ],
    instructions: [
      "Sazona las pechugas de pollo con sal y pimienta.",
      "Bate los huevos en un plato hondo con una pizca de sal.",
      "En otro plato, mezcla el pan rallado con el ajo en polvo y el perejil.",
      "Pasa cada pechuga por huevo batido y luego por la mezcla de pan rallado.",
      "Calienta aceite en una sartén grande a fuego medio-alto.",
      "Fríe las milanesas 4-5 minutos por lado hasta que estén doradas.",
      "Escurre sobre papel absorbente y sirve con rodajas de limón.",
    ],
    prepTime: "15 min",
    cookTime: "20 min",
    servings: 4,
    tags: ["carne", "plato principal", "argentino"],
    image: "chicken-milanesa",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "8",
    name: "Empanadas de Carne",
    description:
      "Clásicas empanadas argentinas rellenas de carne jugosa y especiada.",
    ingredients: [
      { item: "Carne picada", amount: "500g" },
      { item: "Cebolla", amount: "2, picadas" },
      { item: "Cebolla de verdeo", amount: "3, picadas" },
      { item: "Pimentón dulce", amount: "1 cdita" },
      { item: "Comino", amount: "1 cdita" },
      { item: "Huevos duros", amount: "2, picados" },
      { item: "Aceitunas verdes", amount: "12, picadas" },
      { item: "Pasas de uva", amount: "2 cdas (opcional)" },
      { item: "Discos para empanadas", amount: "12 unidades" },
    ],
    instructions: [
      "Sofríe la cebolla en aceite hasta que esté transparente.",
      "Agrega la carne picada y cocina hasta dorar, desmenuzando con cuchara.",
      "Incorpora el pimentón, comino, sal y pimienta. Cocina 2 minutos más.",
      "Retira del fuego y deja enfriar. Agrega cebolla de verdeo, huevo duro y aceitunas.",
      "Coloca una porción de relleno en cada disco, cierra formando un repulgue.",
      "Pincela con huevo batido y hornea a 200°C por 25-30 minutos hasta dorar.",
      "Sirve calientes acompañadas de chimichurri.",
    ],
    prepTime: "30 min",
    cookTime: "30 min",
    servings: 6,
    tags: ["carne", "argentino", "entrada"],
    image: "empanadas-carne",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "9",
    name: "Locro",
    description:
      "Guiso tradicional argentino con maíz, porotos y carne, ideal para días fríos.",
    ingredients: [
      { item: "Maíz blanco", amount: "400g, remojado" },
      { item: "Porotos blancos", amount: "200g, remojados" },
      { item: "Carne de cerdo", amount: "300g, en cubos" },
      { item: "Chorizo colorado", amount: "2 unidades" },
      { item: "Panceta", amount: "150g" },
      { item: "Cebolla", amount: "2, picadas" },
      { item: "Zapallo", amount: "300g, en cubos" },
      { item: "Pimentón", amount: "2 cdas" },
      { item: "Comino", amount: "1 cdita" },
      { item: "Cebolla de verdeo", amount: "para servir" },
    ],
    instructions: [
      "En una olla grande, cocina el maíz y los porotos con abundante agua por 1 hora.",
      "En otra sartén, dora la carne de cerdo y la panceta. Reserva.",
      "Sofríe la cebolla, agrega pimentón y comino.",
      "Incorpora las carnes, el chorizo cortado y el zapallo a la olla con maíz.",
      "Cocina a fuego bajo por 2-3 horas, revolviendo ocasionalmente.",
      "Tritura parte del zapallo para espesar el locro.",
      "Sirve bien caliente con cebolla de verdeo picada por encima.",
    ],
    prepTime: "20 min",
    cookTime: "3 horas",
    servings: 8,
    tags: ["carne", "plato principal", "argentino", "guiso"],
    image: "locro",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "10",
    name: "Humita en Chala",
    description:
      "Delicioso pastel de choclo envuelto en sus propias hojas, suave y aromático.",
    ingredients: [
      { item: "Choclos tiernos", amount: "8 unidades" },
      { item: "Cebolla", amount: "1, picada fina" },
      { item: "Morrón rojo", amount: "1, picado" },
      { item: "Queso fresco", amount: "200g, en cubos" },
      { item: "Manteca", amount: "3 cdas" },
      { item: "Azúcar", amount: "1 cdita" },
      { item: "Pimentón dulce", amount: "1 cdita" },
      { item: "Comino", amount: "una pizca" },
    ],
    instructions: [
      "Desgrana los choclos cuidadosamente, reservando las chalas enteras.",
      "Procesa los granos de choclo hasta obtener una pasta cremosa.",
      "Sofríe la cebolla y el morrón en manteca hasta ablandar.",
      "Agrega el choclo procesado, azúcar, pimentón, comino, sal y pimienta.",
      "Cocina 10 minutos revolviendo hasta espesar ligeramente.",
      "Coloca 2 chalas superpuestas, agrega relleno y un cubo de queso.",
      "Envuelve formando un paquete, ata con tiras de chala y hierve 40 minutos.",
    ],
    prepTime: "40 min",
    cookTime: "50 min",
    servings: 8,
    tags: ["vegetariano", "plato principal", "argentino"],
    image: "humita-chala",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "11",
    name: "Matambre a la Pizza",
    description:
      "Corte de carne relleno con ingredientes de pizza, jugoso y lleno de sabor.",
    ingredients: [
      { item: "Matambre", amount: "1 kg" },
      { item: "Salsa de tomate", amount: "1 taza" },
      { item: "Muzzarella", amount: "300g, en fetas" },
      { item: "Jamón cocido", amount: "150g, en fetas" },
      { item: "Morrón asado", amount: "2, en tiras" },
      { item: "Aceitunas verdes", amount: "100g, picadas" },
      { item: "Orégano", amount: "2 cditas" },
      { item: "Ajo", amount: "3 dientes, picados" },
    ],
    instructions: [
      "Abre el matambre en forma rectangular y sazónalo con sal y pimienta.",
      "Unta la salsa de tomate sobre toda la superficie.",
      "Distribuye el jamón, muzzarella, morrones, aceitunas y ajo.",
      "Espolvorea orégano generosamente.",
      "Enrolla el matambre firmemente desde el lado más largo.",
      "Ata con hilo de cocina cada 3 cm para mantener la forma.",
      "Hornea a 180°C por 1 hora y media. Deja reposar 10 minutos antes de cortar.",
    ],
    prepTime: "25 min",
    cookTime: "90 min",
    servings: 6,
    tags: ["carne", "plato principal", "argentino"],
    image: "matambre-pizza",
    authorName: "Sistema",
    userId: "",
  },
  {
    id: "12",
    name: "Provoleta al Horno",
    description:
      "Queso provolone fundido al horno con hierbas aromáticas, un clásico argentino.",
    ingredients: [
      { item: "Queso provolone", amount: "400g, en rodaja gruesa" },
      { item: "Orégano fresco", amount: "2 cdas" },
      { item: "Aceite de oliva", amount: "2 cdas" },
      { item: "Pimienta negra", amount: "al gusto" },
      { item: "Ají molido", amount: "1/2 cdita" },
    ],
    instructions: [
      "Precalienta el horno a 200°C.",
      "Coloca el queso provolone en una fuente para horno o sartén de hierro.",
      "Espolvorea con orégano y ají molido.",
      "Rocía con aceite de oliva y agrega pimienta al gusto.",
      "Hornea por 10-15 minutos hasta que esté dorado y burbujeante.",
      "Sirve inmediatamente con pan tostado.",
    ],
    prepTime: "5 min",
    cookTime: "15 min",
    servings: 4,
    tags: ["vegetariano", "entrada", "argentino"],
    image: "provoleta",
    authorName: "Sistema",
    userId: "",
  },
];
