import type { Recipe } from './types';

export const recipes: Recipe[] = [
  {
    id: '1',
    name: 'Ensalada de Pasta de Verano',
    description: 'Una ensalada de pasta refrescante y ligera, perfecta para los cálidos días de verano.',
    ingredients: [
      { item: 'Pasta fusilli', amount: '250g' },
      { item: 'Tomates cherry', amount: '200g, partidos a la mitad' },
      { item: 'Pepino', amount: '1, en cubos' },
      { item: 'Queso feta', amount: '100g, desmenuzado' },
      { item: 'Aceite de oliva', amount: '3 cdas' },
      { item: 'Jugo de limón', amount: '1 cda' },
    ],
    instructions: [
      'Cocina la pasta según las instrucciones del paquete. Escúrrela y enjuágala con agua fría.',
      'En un tazón grande, combina la pasta, los tomates, el pepino y el queso feta.',
      'En un tazón pequeño, bate el aceite de oliva y el jugo de limón. Sazona con sal y pimienta.',
      'Vierte el aderezo sobre la ensalada y mezcla para combinar.',
    ],
    prepTime: '15 min',
    cookTime: '10 min',
    servings: 4,
    tags: ['vegetariano', 'ensalada', 'verano'],
    image: 'pasta-salad',
  },
  {
    id: '2',
    name: 'Pollo al Curry Picante',
    description: 'Un rico y aromático pollo al curry con un toque picante.',
    ingredients: [
      { item: 'Pechuga de pollo', amount: '500g, en cubos' },
      { item: 'Cebolla', amount: '1, picada' },
      { item: 'Ajo', amount: '2 dientes, picados' },
      { item: 'Jengibre', amount: '1 pulgada, rallado' },
      { item: 'Leche de coco', amount: '400ml' },
      { item: 'Curry en polvo', amount: '2 cdas' },
    ],
    instructions: [
      'Calienta aceite en una sartén grande. Sofríe la cebolla, el ajo y el jengibre hasta que estén fragantes.',
      'Añade el pollo y cocínalo hasta que se dore.',
      'Incorpora el curry en polvo y cocina por 1 minuto.',
      'Vierte la leche de coco, llévalo a ebullición y cocina a fuego lento durante 15-20 minutos hasta que el pollo esté bien cocido.',
    ],
    prepTime: '10 min',
    cookTime: '25 min',
    servings: 4,
    tags: ['curry', 'picante'],
    image: 'chicken-curry',
  },
  {
    id: '3',
    name: 'Tacos de Frijoles Negros',
    description: 'Tacos veganos sabrosos y satisfactorios con una crema de lima ácida.',
    ingredients: [
      { item: 'Frijoles negros', amount: '1 lata, enjuagados' },
      { item: 'Tortillas de maíz', amount: '8' },
      { item: 'Cebolla roja', amount: '1/2, en cubos' },
      { item: 'Cilantro', amount: '1/4 taza, picado' },
      { item: 'Aguacate', amount: '1, en rodajas' },
      { item: 'Lima', amount: '1, el jugo' },
    ],
    instructions: [
      'En un tazón, machaca la mitad de los frijoles negros. Mezcla los frijoles enteros, la cebolla y el cilantro.',
      'Calienta las tortillas en una sartén seca.',
      'Reparte la mezcla de frijoles en las tortillas.',
      'Cubre con rodajas de aguacate y un chorrito de jugo de lima.',
    ],
    prepTime: '20 min',
    cookTime: '5 min',
    servings: 2,
    tags: ['vegano', 'tacos', 'mexicano'],
    image: 'vegan-tacos',
  },
  {
    id: '4',
    name: 'Pastel de Chocolate Decadente',
    description: 'Un pastel de chocolate húmedo y chocolatoso que es sorprendentemente fácil de hacer.',
    ingredients: [
      { item: 'Harina para todo uso', amount: '2 tazas' },
      { item: 'Azúcar', amount: '2 tazas' },
      { item: 'Cacao en polvo sin azúcar', amount: '3/4 taza' },
      { item: 'Bicarbonato de sodio', amount: '2 cditas' },
      { item: 'Huevos', amount: '2' },
      { item: 'Suero de leche', amount: '1 taza' },
    ],
    instructions: [
      'Precalienta el horno a 350°F (175°C). Engrasa y enharina dos moldes redondos de 9 pulgadas.',
      'En un tazón grande, mezcla la harina, el azúcar, el cacao, el bicarbonato de sodio y la sal.',
      'Añade los huevos, el suero de leche, el aceite y la vainilla. Bate a velocidad media durante 2 minutos.',
      'Incorpora el agua hirviendo. La masa estará líquida.',
      'Vierte uniformemente en los moldes preparados.',
      'Hornea de 30 a 35 minutos.',
    ],
    prepTime: '20 min',
    cookTime: '35 min',
    servings: 12,
    tags: ['postre', 'pastel', 'chocolate'],
    image: 'chocolate-cake',
  },
  {
    id: '5',
    name: 'Tostada Clásica de Aguacate',
    description: 'Un desayuno o snack simple, saludable y delicioso.',
    ingredients: [
      { item: 'Pan de masa madre', amount: '2 rebanadas' },
      { item: 'Aguacate', amount: '1, maduro' },
      { item: 'Huevo', amount: '1' },
      { item: 'Hojuelas de pimiento rojo', amount: 'una pizca' },
    ],
    instructions: [
      'Tuesta el pan de masa madre a tu gusto.',
      'Machaca el aguacate y úntalo sobre la tostada.',
      'Escalfa o fríe un huevo y colócalo encima del aguacate.',
      'Espolvorea con hojuelas de pimiento rojo, sal y pimienta.',
    ],
    prepTime: '5 min',
    cookTime: '5 min',
    servings: 1,
    tags: ['desayuno', 'vegetariano', 'saludable'],
    image: 'avocado-toast',
  },
  {
    id: '6',
    name: 'Salmón a la Parrilla Simple',
    description: 'Un plato principal rápido y elegante de salmón con limón y hierbas.',
    ingredients: [
      { item: 'Filetes de salmón', amount: '2' },
      { item: 'Aceite de oliva', amount: '1 cda' },
      { item: 'Limón', amount: '1' },
      { item: 'Eneldo fresco', amount: '2 ramitas' },
    ],
    instructions: [
      'Precalienta la parrilla a fuego medio-alto.',
      'Unta el salmón con aceite de oliva y sazona con sal y pimienta.',
      'Asa con la piel hacia abajo durante 5-7 minutos.',
      'Voltea y cocina por otros 3-5 minutos, hasta que esté bien cocido.',
      'Sirve con un chorrito de limón y eneldo fresco.',
    ],
    prepTime: '5 min',
    cookTime: '12 min',
    servings: 2,
    tags: ['saludable', 'pescados y mariscos', 'sin gluten'],
    image: 'grilled-salmon',
  },
];
